### ISSUE TITLE
Crash on second start in finch

### ISSUE THREAD

**Issue by vitalyster** [ars3niy/tdlib-purple#54]
Everything works for me on first start and authorization, but I get segmentation fault on next launch:
```
#0  __strlen_sse2 () at ../sysdeps/x86_64/multiarch/../strlen.S:120
#1  0x00007f44930daf9c in std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare(char const*) const () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x00007f448198db79 in std::operator==<char, std::char_traits<char>, std::allocator<char> > (__rhs=0x0,
    __lhs="") at /usr/include/c++/8/bits/basic_string.h:6120
#3  std::operator!=<char, std::char_traits<char>, std::allocator<char> > (__rhs=0x0, __lhs="")
    at /usr/include/c++/8/bits/basic_string.h:6122
#4  updatePrivateChat (account=..., chat=..., user=...) at ./client-utils.cpp:238
#5  0x00007f448197b241 in PurpleTdClient::updateUserInfo (this=0x5563440daf00, user=...,
    privateChat=0x7f4454192b90) at ./td-client.cpp:1535
#6  0x00007f448197bbae in PurpleTdClient::updateChat (chat=0x7f4454192b90, this=0x5563440daf00)
    at ./td-client.cpp:1514
#7  PurpleTdClient::updateChat (this=0x5563440daf00, chat=0x7f4454192b90) at ./td-client.cpp:1495
#8  0x00007f448197bd2b in PurpleTdClient::updatePurpleChatListAndReportConnected (this=0x5563440daf00)
    at ./td-client.cpp:763
#9  0x00007f448197c085 in PurpleTdClient::requestMissingPrivateChats (this=0x5563440daf00)
    at ./td-client.cpp:660
#10 0x00007f448197c30d in PurpleTdClient::loginCreatePrivateChatResponse (this=0x5563440daf00,
    requestId=<optimized out>, object=...) at ./td-client.cpp:682
#11 0x00007f44819835b8 in TdTransceiverImpl::rxCallback (user_data=0x7f4458009950)
    at /usr/include/td/tl/TlObject.h:131
#12 0x00007f449686fdd8 in g_main_context_dispatch () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#13 0x00007f44968701c8 in ?? () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#14 0x00007f44968704c2 in g_main_loop_run () from /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#15 0x000055634245943c in main (argc=1, argv=0x7ffec5a87c38) at ././finch/finch.c:457
```
Using your Debian 10 packages from OBS

**Comment by ars3niy** [comment]
I've fixed the problem here in the repository, but cannot build new packages yet because the build service is down.

**Comment by ars3niy** [comment]
Actually, you can try the new package now.

**Comment by vitalyster** [comment]
It works now, thanks
